export const BOOKS_GET_REQUEST = 'BOOKS_GET_REQUEST';
export const BOOKS_GET_SUCCESS = 'BOOKS_GET_SUCCESS';
export const BOOKS_GET_FAIL = 'BOOKS_GET_FAIL';
export const BOOK_GET_BY_ID_SUCCESS = 'BOOK_GET_BY_ID_SUCCESS';
export const BOOK_GET_BY_ID_FAIL = 'BOOK_GET_BY_ID_FAIL';
export const BOOK_SEARCH = 'BOOK_SEARCH';
export const BOOK_FILTER_BY_PRICE = 'BOOK_FILTER_BY_PRICE';
